version: '3.8'
services:
  db:
    image: mysql:5.7
    container_name: wp-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wp1234
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    build: ./docker
    container_name: wp-site
    depends_on:
      - db
    ports:
      - "9090:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wp1234
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wordpress:/var/www/html

volumes:
  db_data:

